// Copyright 2018 The CRT Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build none

package main

import (
	"fmt"
	"log"
	"os/exec"
	"runtime"
	"sort"
	"strings"

	"modernc.org/crt"
)

/*

#include <ctype.h>
#include <locale.h>

*/
import "C"

const (
	isalnum = 1 << iota
	isalpha
	isblank
	iscntrl
	isdigit
	isgraph
	islower
	isprint
	ispunct
	isspace
	isupper
	isxdigit
)

func main() {
	log.SetFlags(log.Flags() | log.Lshortfile)
	b, err := exec.Command("locale", "-a").Output()
	if err != nil {
		log.Fatal(err)
	}

	s := strings.TrimSpace(string(b))
	a := strings.Split(s, "\n")
	sort.Strings(a)
	runtime.LockOSThread()
	fmt.Printf(`// Code generated by 'go run ctype_gen.go > tmp && mv tmp ctype.go', DO NOT EDIT.

package crt

const (
	isalnum = 1 << iota
	isalpha
	isblank
	iscntrl
	isdigit
	isgraph
	islower
	isprint
	ispunct
	isspace
	isupper
	isxdigit
)

var (
	currentLocale = ctype["C"]
	ctype = map[string]*[256]uint16{
`)
	for _, locale := range a {
		r := C.GoString(C.setlocale(C.LC_CTYPE, C.CString(locale)))
		if r != locale {
			log.Printf("cannot set locale to %s", locale)
			continue
		}

		fmt.Printf(`
	%q: {
`, locale)
		for i := 0; ; i++ {
			i := C.int(i)
			if i == 256 {
				i = crt.DEOF
			}
			var bits uint16
			if C.isalnum(i) != 0 {
				bits |= isalnum
			}
			if C.isalpha(i) != 0 {
				bits |= isalpha
			}
			if C.isblank(i) != 0 {
				bits |= isblank
			}
			if C.iscntrl(i) != 0 {
				bits |= iscntrl
			}
			if C.isdigit(i) != 0 {
				bits |= isdigit
			}
			if C.isgraph(i) != 0 {
				bits |= isgraph
			}
			if C.islower(i) != 0 {
				bits |= islower
			}
			if C.isprint(i) != 0 {
				bits |= isprint
			}
			if C.ispunct(i) != 0 {
				bits |= ispunct
			}
			if C.isspace(i) != 0 {
				bits |= isspace
			}
			if C.isupper(i) != 0 {
				bits |= isupper
			}
			if C.isxdigit(i) != 0 {
				bits |= isxdigit
			}
			if i == crt.DEOF {
				if bits != 0 {
					log.Fatal("internal error")
				}

				break
			}

			fmt.Printf("%#03x, ", bits)
			if (i+1)%16 == 0 && i != 255 {
				fmt.Printf("\n")
			}
		}
		fmt.Printf("\n},")
		// for i := 0; i < 256; i++ {
		// 	// p.tolower = int(C.tolower(i))
		// 	// p.toupper = int(C.toupper(i))
		// }
	}
	fmt.Printf("\n}")
	fmt.Printf("\n)")
}
