// Code generated by 'ccgo /tmp/go-generate-358883214/x.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-pkgname mman -o libc/sys/mman/mman_linux_amd64.go', DO NOT EDIT.

package mman

var CAPI = map[string]struct{}{}
