// Code generated by 'ccgo /tmp/go-generate-358883214/x.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-pkgname mman -o libc/sys/mman/mman_linux_amd64.go', DO NOT EDIT.

package mman

import (
	"math"
	"reflect"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ unsafe.Pointer

const (
	MADV_DODUMP           = 17
	MADV_DOFORK           = 11
	MADV_DONTDUMP         = 16
	MADV_DONTFORK         = 10
	MADV_DONTNEED         = 4
	MADV_FREE             = 8
	MADV_HUGEPAGE         = 14
	MADV_HWPOISON         = 100
	MADV_KEEPONFORK       = 19
	MADV_MERGEABLE        = 12
	MADV_NOHUGEPAGE       = 15
	MADV_NORMAL           = 0
	MADV_RANDOM           = 1
	MADV_REMOVE           = 9
	MADV_SEQUENTIAL       = 2
	MADV_UNMERGEABLE      = 13
	MADV_WILLNEED         = 3
	MADV_WIPEONFORK       = 18
	MAP_32BIT             = 0x40
	MAP_ANON              = 32
	MAP_ANONYMOUS         = 0x20
	MAP_DENYWRITE         = 0x00800
	MAP_EXECUTABLE        = 0x01000
	MAP_FILE              = 0
	MAP_FIXED             = 0x10
	MAP_FIXED_NOREPLACE   = 0x100000
	MAP_GROWSDOWN         = 0x00100
	MAP_HUGETLB           = 0x40000
	MAP_HUGE_MASK         = 0x3
	MAP_HUGE_SHIFT        = 26
	MAP_LOCKED            = 0x02000
	MAP_NONBLOCK          = 0x10000
	MAP_NORESERVE         = 0x04000
	MAP_POPULATE          = 0x08000
	MAP_PRIVATE           = 0x02
	MAP_SHARED            = 0x01
	MAP_SHARED_VALIDATE   = 0x03
	MAP_STACK             = 0x20000
	MAP_SYNC              = 0x80000
	MAP_TYPE              = 0x0
	MCL_CURRENT           = 1
	MCL_FUTURE            = 2
	MCL_ONFAULT           = 4
	MS_ASYNC              = 1
	MS_INVALIDATE         = 2
	MS_SYNC               = 4
	POSIX_MADV_DONTNEED   = 4
	POSIX_MADV_NORMAL     = 0
	POSIX_MADV_RANDOM     = 1
	POSIX_MADV_SEQUENTIAL = 2
	POSIX_MADV_WILLNEED   = 3
	PROT_EXEC             = 0x4
	PROT_GROWSDOWN        = 0x01000000
	PROT_GROWSUP          = 0x02000000
	PROT_NONE             = 0x0
	PROT_READ             = 0x1
	PROT_WRITE            = 0x2
	X_ATFILE_SOURCE       = 1
	X_BITS_TYPESIZES_H    = 1
	X_BITS_TYPES_H        = 1
	X_BSD_SIZE_T_         = 0
	X_BSD_SIZE_T_DEFINED_ = 0
	X_DEFAULT_SOURCE      = 1
	X_FEATURES_H          = 1
	X_GCC_SIZE_T          = 0
	X_LP64                = 1
	X_POSIX_C_SOURCE      = 200809
	X_POSIX_SOURCE        = 1
	X_SIZET_              = 0
	X_SIZE_T              = 0
	X_SIZE_T_             = 0
	X_SIZE_T_DECLARED     = 0
	X_SIZE_T_DEFINED      = 0
	X_SIZE_T_DEFINED_     = 0
	X_STDC_PREDEF_H       = 1
	X_SYS_CDEFS_H         = 1
	X_SYS_MMAN_H          = 1
	X_SYS_SIZE_T_H        = 0
	X_T_SIZE              = 0
	X_T_SIZE_             = 0
	Linux                 = 1
	Unix                  = 1
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

// Wide character type.
//   Locale-writers should change this as necessary to
//   be big enough to hold unique values not between 0 and 127,
//   and not (wchar_t) -1, for each defined multibyte character.

// Define this type if we are doing the whole job,
//   or if we want this type in particular.

//  In 4.3bsd-net2, leave these undefined to indicate that size_t, etc.
//    are already defined.
//  BSD/OS 3.1 and FreeBSD [23].x require the MACHINE_ANSI_H check here.
//  NetBSD 5 requires the I386_ANSI_H and X86_64_ANSI_H checks here.

// A null pointer constant.

type Off_t = int64 /* mman.h:29:17 */

type Mode_t = uint32 /* mman.h:37:18 */

var _ int8 /* x.c:2:13: */
