// Code generated by running "go generate". DO NOT EDIT.

package sched // import "github.com/next-bin/go-sqlite/v2/ccir/libc/sched"

const (
	X_BITS_TYPES_H  = 1
	X_SCHED_H       = 1
	X__S32_TYPE     = 0
	X__SLONG32_TYPE = 0
	Xsched_priority = 0
)
