// Code generated by `gocc /tmp/go-generate-827115141/x.c -o libc/errno/errno_linux_amd64.go -qbec-defines -qbec-enumconsts -qbec-import <none> -qbec-pkgname errno -qbec-structs`, DO NOT EDIT.

package errno

const (
	DE2BIG                            = 7
	DEACCES                           = 13
	DEADDRINUSE                       = 98
	DEADDRNOTAVAIL                    = 99
	DEADV                             = 68
	DEAFNOSUPPORT                     = 97
	DEAGAIN                           = 11
	DEALREADY                         = 114
	DEBADE                            = 52
	DEBADF                            = 9
	DEBADFD                           = 77
	DEBADMSG                          = 74
	DEBADR                            = 53
	DEBADRQC                          = 56
	DEBADSLT                          = 57
	DEBFONT                           = 59
	DEBUSY                            = 16
	DECANCELED                        = 125
	DECHILD                           = 10
	DECHRNG                           = 44
	DECOMM                            = 70
	DECONNABORTED                     = 103
	DECONNREFUSED                     = 111
	DECONNRESET                       = 104
	DEDEADLK                          = 35
	DEDEADLOCK                        = 35
	DEDESTADDRREQ                     = 89
	DEDOM                             = 33
	DEDOTDOT                          = 73
	DEDQUOT                           = 122
	DEEXIST                           = 17
	DEFAULT                           = 14
	DEFBIG                            = 27
	DEHOSTDOWN                        = 112
	DEHOSTUNREACH                     = 113
	DEHWPOISON                        = 133
	DEIDRM                            = 43
	DEILSEQ                           = 84
	DEINPROGRESS                      = 115
	DEINTR                            = 4
	DEINVAL                           = 22
	DEIO                              = 5
	DEISCONN                          = 106
	DEISDIR                           = 21
	DEISNAM                           = 120
	DEKEYEXPIRED                      = 127
	DEKEYREJECTED                     = 129
	DEKEYREVOKED                      = 128
	DEL2HLT                           = 51
	DEL2NSYNC                         = 45
	DEL3HLT                           = 46
	DEL3RST                           = 47
	DELIBACC                          = 79
	DELIBBAD                          = 80
	DELIBEXEC                         = 83
	DELIBMAX                          = 82
	DELIBSCN                          = 81
	DELNRNG                           = 48
	DELOOP                            = 40
	DEMEDIUMTYPE                      = 124
	DEMFILE                           = 24
	DEMLINK                           = 31
	DEMSGSIZE                         = 90
	DEMULTIHOP                        = 72
	DENAMETOOLONG                     = 36
	DENAVAIL                          = 119
	DENETDOWN                         = 100
	DENETRESET                        = 102
	DENETUNREACH                      = 101
	DENFILE                           = 23
	DENOANO                           = 55
	DENOBUFS                          = 105
	DENOCSI                           = 50
	DENODATA                          = 61
	DENODEV                           = 19
	DENOENT                           = 2
	DENOEXEC                          = 8
	DENOKEY                           = 126
	DENOLCK                           = 37
	DENOLINK                          = 67
	DENOMEDIUM                        = 123
	DENOMEM                           = 12
	DENOMSG                           = 42
	DENONET                           = 64
	DENOPKG                           = 65
	DENOPROTOOPT                      = 92
	DENOSPC                           = 28
	DENOSR                            = 63
	DENOSTR                           = 60
	DENOSYS                           = 38
	DENOTBLK                          = 15
	DENOTCONN                         = 107
	DENOTDIR                          = 20
	DENOTEMPTY                        = 39
	DENOTNAM                          = 118
	DENOTRECOVERABLE                  = 131
	DENOTSOCK                         = 88
	DENOTSUP                          = 95
	DENOTTY                           = 25
	DENOTUNIQ                         = 76
	DENXIO                            = 6
	DEOPNOTSUPP                       = 95
	DEOVERFLOW                        = 75
	DEOWNERDEAD                       = 130
	DEPERM                            = 1
	DEPFNOSUPPORT                     = 96
	DEPIPE                            = 32
	DEPROTO                           = 71
	DEPROTONOSUPPORT                  = 93
	DEPROTOTYPE                       = 91
	DERANGE                           = 34
	DEREMCHG                          = 78
	DEREMOTE                          = 66
	DEREMOTEIO                        = 121
	DERESTART                         = 85
	DERFKILL                          = 132
	DEROFS                            = 30
	DESHUTDOWN                        = 108
	DESOCKTNOSUPPORT                  = 94
	DESPIPE                           = 29
	DESRCH                            = 3
	DESRMNT                           = 69
	DESTALE                           = 116
	DESTRPIPE                         = 86
	DETIME                            = 62
	DETIMEDOUT                        = 110
	DETOOMANYREFS                     = 109
	DETXTBSY                          = 26
	DEUCLEAN                          = 117
	DEUNATCH                          = 49
	DEUSERS                           = 87
	DEWOULDBLOCK                      = 11
	DEXDEV                            = 18
	DEXFULL                           = 54
	D_ASM_GENERIC_ERRNO_BASE_H        = 0
	D_ASM_GENERIC_ERRNO_H             = 0
	D_ATFILE_SOURCE                   = 1
	D_BITS_ERRNO_H                    = 1
	D_DEFAULT_SOURCE                  = 1
	D_ERRNO_H                         = 1
	D_FEATURES_H                      = 1
	D_LP64                            = 1
	D_POSIX_C_SOURCE                  = 200809
	D_POSIX_SOURCE                    = 1
	D_STDC_PREDEF_H                   = 1
	D_SYS_CDEFS_H                     = 1
	D__ATOMIC_ACQUIRE                 = 2
	D__ATOMIC_ACQ_REL                 = 4
	D__ATOMIC_CONSUME                 = 1
	D__ATOMIC_HLE_ACQUIRE             = 65536
	D__ATOMIC_HLE_RELEASE             = 131072
	D__ATOMIC_RELAXED                 = 0
	D__ATOMIC_RELEASE                 = 3
	D__ATOMIC_SEQ_CST                 = 5
	D__BEGIN_DECLS                    = 0
	D__BIGGEST_ALIGNMENT__            = 16
	D__BYTE_ORDER__                   = 1234
	D__CHAR_BIT__                     = 8
	D__COUNTER__                      = 0
	D__DBL_DECIMAL_DIG__              = 17
	D__DBL_DIG__                      = 15
	D__DBL_HAS_DENORM__               = 1
	D__DBL_HAS_INFINITY__             = 1
	D__DBL_HAS_QUIET_NAN__            = 1
	D__DBL_MANT_DIG__                 = 53
	D__DBL_MAX_10_EXP__               = 308
	D__DBL_MAX_EXP__                  = 1024
	D__DBL_MIN_10_EXP__               = -307
	D__DBL_MIN_EXP__                  = -1021
	D__DEC128_MANT_DIG__              = 34
	D__DEC128_MAX_EXP__               = 6145
	D__DEC128_MIN_EXP__               = -6142
	D__DEC32_MANT_DIG__               = 7
	D__DEC32_MAX_EXP__                = 97
	D__DEC32_MIN_EXP__                = -94
	D__DEC64_MANT_DIG__               = 16
	D__DEC64_MAX_EXP__                = 385
	D__DEC64_MIN_EXP__                = -382
	D__DECIMAL_BID_FORMAT__           = 1
	D__DECIMAL_DIG__                  = 21
	D__DEC_EVAL_METHOD__              = 2
	D__DI__                           = 0
	D__ELF__                          = 1
	D__END_DECLS                      = 0
	D__FINITE_MATH_ONLY__             = 0
	D__FLOAT_WORD_ORDER__             = 1234
	D__FLT128_DECIMAL_DIG__           = 36
	D__FLT128_DIG__                   = 33
	D__FLT128_HAS_DENORM__            = 1
	D__FLT128_HAS_INFINITY__          = 1
	D__FLT128_HAS_QUIET_NAN__         = 1
	D__FLT128_MANT_DIG__              = 113
	D__FLT128_MAX_10_EXP__            = 4932
	D__FLT128_MAX_EXP__               = 16384
	D__FLT128_MIN_10_EXP__            = -4931
	D__FLT128_MIN_EXP__               = -16381
	D__FLT32X_DECIMAL_DIG__           = 17
	D__FLT32X_DIG__                   = 15
	D__FLT32X_HAS_DENORM__            = 1
	D__FLT32X_HAS_INFINITY__          = 1
	D__FLT32X_HAS_QUIET_NAN__         = 1
	D__FLT32X_MANT_DIG__              = 53
	D__FLT32X_MAX_10_EXP__            = 308
	D__FLT32X_MAX_EXP__               = 1024
	D__FLT32X_MIN_10_EXP__            = -307
	D__FLT32X_MIN_EXP__               = -1021
	D__FLT32_DECIMAL_DIG__            = 9
	D__FLT32_DIG__                    = 6
	D__FLT32_HAS_DENORM__             = 1
	D__FLT32_HAS_INFINITY__           = 1
	D__FLT32_HAS_QUIET_NAN__          = 1
	D__FLT32_MANT_DIG__               = 24
	D__FLT32_MAX_10_EXP__             = 38
	D__FLT32_MAX_EXP__                = 128
	D__FLT32_MIN_10_EXP__             = -37
	D__FLT32_MIN_EXP__                = -125
	D__FLT64X_DECIMAL_DIG__           = 21
	D__FLT64X_DIG__                   = 18
	D__FLT64X_HAS_DENORM__            = 1
	D__FLT64X_HAS_INFINITY__          = 1
	D__FLT64X_HAS_QUIET_NAN__         = 1
	D__FLT64X_MANT_DIG__              = 64
	D__FLT64X_MAX_10_EXP__            = 4932
	D__FLT64X_MAX_EXP__               = 16384
	D__FLT64X_MIN_10_EXP__            = -4931
	D__FLT64X_MIN_EXP__               = -16381
	D__FLT64_DECIMAL_DIG__            = 17
	D__FLT64_DIG__                    = 15
	D__FLT64_HAS_DENORM__             = 1
	D__FLT64_HAS_INFINITY__           = 1
	D__FLT64_HAS_QUIET_NAN__          = 1
	D__FLT64_MANT_DIG__               = 53
	D__FLT64_MAX_10_EXP__             = 308
	D__FLT64_MAX_EXP__                = 1024
	D__FLT64_MIN_10_EXP__             = -307
	D__FLT64_MIN_EXP__                = -1021
	D__FLT_DECIMAL_DIG__              = 9
	D__FLT_DIG__                      = 6
	D__FLT_EVAL_METHOD_TS_18661_3__   = 0
	D__FLT_EVAL_METHOD__              = 0
	D__FLT_HAS_DENORM__               = 1
	D__FLT_HAS_INFINITY__             = 1
	D__FLT_HAS_QUIET_NAN__            = 1
	D__FLT_MANT_DIG__                 = 24
	D__FLT_MAX_10_EXP__               = 38
	D__FLT_MAX_EXP__                  = 128
	D__FLT_MIN_10_EXP__               = -37
	D__FLT_MIN_EXP__                  = -125
	D__FLT_RADIX__                    = 2
	D__FXSR__                         = 1
	D__GLIBC_MINOR__                  = 26
	D__GLIBC_USE_DEPRECATED_GETS      = 0
	D__GLIBC__                        = 2
	D__GNU_LIBRARY__                  = 6
	D__GXX_ABI_VERSION                = 1011
	D__HAVE_GENERIC_SELECTION         = 1
	D__HI__                           = 0
	D__INT16_MAX__                    = 32767
	D__INT32_MAX__                    = 2147483647
	D__INT64_MAX__                    = 9223372036854775807
	D__INT8_MAX__                     = 127
	D__INTMAX_MAX__                   = 9223372036854775807
	D__INTMAX_WIDTH__                 = 64
	D__INTPTR_MAX__                   = 9223372036854775807
	D__INTPTR_WIDTH__                 = 64
	D__INT_FAST16_MAX__               = 9223372036854775807
	D__INT_FAST16_WIDTH__             = 64
	D__INT_FAST32_MAX__               = 9223372036854775807
	D__INT_FAST32_WIDTH__             = 64
	D__INT_FAST64_MAX__               = 9223372036854775807
	D__INT_FAST64_WIDTH__             = 64
	D__INT_FAST8_MAX__                = 127
	D__INT_FAST8_WIDTH__              = 8
	D__INT_LEAST16_MAX__              = 32767
	D__INT_LEAST16_WIDTH__            = 16
	D__INT_LEAST32_MAX__              = 2147483647
	D__INT_LEAST32_WIDTH__            = 32
	D__INT_LEAST64_MAX__              = 9223372036854775807
	D__INT_LEAST64_WIDTH__            = 64
	D__INT_LEAST8_MAX__               = 127
	D__INT_LEAST8_WIDTH__             = 8
	D__INT_MAX__                      = 2147483647
	D__INT_WIDTH__                    = 32
	D__KERNEL_STRICT_NAMES            = 0
	D__LDBL_DECIMAL_DIG__             = 21
	D__LDBL_DIG__                     = 18
	D__LDBL_HAS_DENORM__              = 1
	D__LDBL_HAS_INFINITY__            = 1
	D__LDBL_HAS_QUIET_NAN__           = 1
	D__LDBL_MANT_DIG__                = 64
	D__LDBL_MAX_10_EXP__              = 4932
	D__LDBL_MAX_EXP__                 = 16384
	D__LDBL_MIN_10_EXP__              = -4931
	D__LDBL_MIN_EXP__                 = -16381
	D__LINE__                         = 0
	D__LONG_LONG_MAX__                = 9223372036854775807
	D__LONG_LONG_WIDTH__              = 64
	D__LONG_MAX__                     = 9223372036854775807
	D__LONG_WIDTH__                   = 64
	D__LP64__                         = 1
	D__MMX__                          = 1
	D__NO_INLINE__                    = 1
	D__ORDER_BIG_ENDIAN__             = 4321
	D__ORDER_LITTLE_ENDIAN__          = 1234
	D__ORDER_PDP_ENDIAN__             = 3412
	D__PRAGMA_REDEFINE_EXTNAME        = 1
	D__PTRDIFF_MAX__                  = 9223372036854775807
	D__PTRDIFF_WIDTH__                = 64
	D__QI__                           = 0
	D__REGISTER_PREFIX__              = 0
	D__SCHAR_MAX__                    = 127
	D__SCHAR_WIDTH__                  = 8
	D__SEG_FS                         = 1
	D__SEG_GS                         = 1
	D__SHRT_MAX__                     = 32767
	D__SHRT_WIDTH__                   = 16
	D__SIG_ATOMIC_MAX__               = 2147483647
	D__SIG_ATOMIC_MIN__               = -2147483648
	D__SIG_ATOMIC_WIDTH__             = 32
	D__SIZEOF_DOUBLE__                = 8
	D__SIZEOF_FLOAT128__              = 16
	D__SIZEOF_FLOAT80__               = 16
	D__SIZEOF_FLOAT__                 = 4
	D__SIZEOF_INT128__                = 16
	D__SIZEOF_INT__                   = 4
	D__SIZEOF_LONG_DOUBLE__           = 16
	D__SIZEOF_LONG_LONG__             = 8
	D__SIZEOF_LONG__                  = 8
	D__SIZEOF_POINTER__               = 8
	D__SIZEOF_PTRDIFF_T__             = 8
	D__SIZEOF_SHORT__                 = 2
	D__SIZEOF_SIZE_T__                = 8
	D__SIZEOF_WCHAR_T__               = 4
	D__SIZEOF_WINT_T__                = 4
	D__SIZE_MAX__                     = 18446744073709551615
	D__SIZE_WIDTH__                   = 64
	D__SI__                           = 0
	D__SSE2_MATH__                    = 1
	D__SSE2__                         = 1
	D__SSE_MATH__                     = 1
	D__SSE__                          = 1
	D__STDC_HOSTED__                  = 1
	D__STDC_IEC_559_COMPLEX__         = 1
	D__STDC_IEC_559__                 = 1
	D__STDC_ISO_10646__               = 201706
	D__STDC_NO_THREADS__              = 1
	D__STDC_UTF_16__                  = 1
	D__STDC_UTF_32__                  = 1
	D__STDC_VERSION__                 = 201112
	D__STDC__                         = 1
	D__SYSCALL_WORDSIZE               = 64
	D__THROW                          = 0
	D__THROWNL                        = 0
	D__UINT16_MAX__                   = 65535
	D__UINT32_MAX__                   = 4294967295
	D__UINT64_MAX__                   = 18446744073709551615
	D__UINT8_MAX__                    = 255
	D__UINTMAX_MAX__                  = 18446744073709551615
	D__UINTPTR_MAX__                  = 18446744073709551615
	D__UINT_FAST16_MAX__              = 18446744073709551615
	D__UINT_FAST32_MAX__              = 18446744073709551615
	D__UINT_FAST64_MAX__              = 18446744073709551615
	D__UINT_FAST8_MAX__               = 255
	D__UINT_LEAST16_MAX__             = 65535
	D__UINT_LEAST32_MAX__             = 4294967295
	D__UINT_LEAST64_MAX__             = 18446744073709551615
	D__UINT_LEAST8_MAX__              = 255
	D__USER_LABEL_PREFIX__            = 0
	D__USE_ATFILE                     = 1
	D__USE_FORTIFY_LEVEL              = 0
	D__USE_ISOC11                     = 1
	D__USE_ISOC95                     = 1
	D__USE_ISOC99                     = 1
	D__USE_MISC                       = 1
	D__USE_POSIX                      = 1
	D__USE_POSIX199309                = 1
	D__USE_POSIX199506                = 1
	D__USE_POSIX2                     = 1
	D__USE_POSIX_IMPLICITLY           = 1
	D__USE_XOPEN2K                    = 1
	D__USE_XOPEN2K8                   = 1
	D__WCHAR_MAX__                    = 2147483647
	D__WCHAR_MIN__                    = -2147483648
	D__WCHAR_WIDTH__                  = 32
	D__WINT_MAX__                     = 4294967295
	D__WINT_MIN__                     = 0
	D__WINT_WIDTH__                   = 32
	D__WORDSIZE                       = 64
	D__WORDSIZE_TIME64_COMPAT32       = 1
	D__always_inline                  = 0
	D__amd64                          = 1
	D__amd64__                        = 1
	D__attribute_artificial__         = 0
	D__attribute_const__              = 0
	D__attribute_deprecated__         = 0
	D__attribute_malloc__             = 0
	D__attribute_noinline__           = 0
	D__attribute_pure__               = 0
	D__attribute_used__               = 0
	D__attribute_warn_unused_result__ = 0
	D__code_model_small__             = 1
	D__extension__                    = 0
	D__glibc_c99_flexarr_available    = 1
	D__inline                         = 0
	D__k8                             = 1
	D__k8__                           = 1
	D__linux                          = 1
	D__linux__                        = 1
	D__restrict                       = 0
	D__stub___compat_bdflush          = 0
	D__stub_chflags                   = 0
	D__stub_fattach                   = 0
	D__stub_fchflags                  = 0
	D__stub_fdetach                   = 0
	D__stub_getmsg                    = 0
	D__stub_gtty                      = 0
	D__stub_lchmod                    = 0
	D__stub_putmsg                    = 0
	D__stub_revoke                    = 0
	D__stub_setlogin                  = 0
	D__stub_sigreturn                 = 0
	D__stub_sstk                      = 0
	D__stub_stty                      = 0
	D__unix                           = 1
	D__unix__                         = 1
	D__word__                         = 0
	D__wur                            = 0
	D__x86_64                         = 1
	D__x86_64__                       = 1
	Dlinux                            = 1
	Dunix                             = 1
)

var Config = map[string]string{
	"E2BIG":                            "7",
	"EACCES":                           "13",
	"EADDRINUSE":                       "98",
	"EADDRNOTAVAIL":                    "99",
	"EADV":                             "68",
	"EAFNOSUPPORT":                     "97",
	"EAGAIN":                           "11",
	"EALREADY":                         "114",
	"EBADE":                            "52",
	"EBADF":                            "9",
	"EBADFD":                           "77",
	"EBADMSG":                          "74",
	"EBADR":                            "53",
	"EBADRQC":                          "56",
	"EBADSLT":                          "57",
	"EBFONT":                           "59",
	"EBUSY":                            "16",
	"ECANCELED":                        "125",
	"ECHILD":                           "10",
	"ECHRNG":                           "44",
	"ECOMM":                            "70",
	"ECONNABORTED":                     "103",
	"ECONNREFUSED":                     "111",
	"ECONNRESET":                       "104",
	"EDEADLK":                          "35",
	"EDEADLOCK":                        "35",
	"EDESTADDRREQ":                     "89",
	"EDOM":                             "33",
	"EDOTDOT":                          "73",
	"EDQUOT":                           "122",
	"EEXIST":                           "17",
	"EFAULT":                           "14",
	"EFBIG":                            "27",
	"EHOSTDOWN":                        "112",
	"EHOSTUNREACH":                     "113",
	"EHWPOISON":                        "133",
	"EIDRM":                            "43",
	"EILSEQ":                           "84",
	"EINPROGRESS":                      "115",
	"EINTR":                            "4",
	"EINVAL":                           "22",
	"EIO":                              "5",
	"EISCONN":                          "106",
	"EISDIR":                           "21",
	"EISNAM":                           "120",
	"EKEYEXPIRED":                      "127",
	"EKEYREJECTED":                     "129",
	"EKEYREVOKED":                      "128",
	"EL2HLT":                           "51",
	"EL2NSYNC":                         "45",
	"EL3HLT":                           "46",
	"EL3RST":                           "47",
	"ELIBACC":                          "79",
	"ELIBBAD":                          "80",
	"ELIBEXEC":                         "83",
	"ELIBMAX":                          "82",
	"ELIBSCN":                          "81",
	"ELNRNG":                           "48",
	"ELOOP":                            "40",
	"EMEDIUMTYPE":                      "124",
	"EMFILE":                           "24",
	"EMLINK":                           "31",
	"EMSGSIZE":                         "90",
	"EMULTIHOP":                        "72",
	"ENAMETOOLONG":                     "36",
	"ENAVAIL":                          "119",
	"ENETDOWN":                         "100",
	"ENETRESET":                        "102",
	"ENETUNREACH":                      "101",
	"ENFILE":                           "23",
	"ENOANO":                           "55",
	"ENOBUFS":                          "105",
	"ENOCSI":                           "50",
	"ENODATA":                          "61",
	"ENODEV":                           "19",
	"ENOENT":                           "2",
	"ENOEXEC":                          "8",
	"ENOKEY":                           "126",
	"ENOLCK":                           "37",
	"ENOLINK":                          "67",
	"ENOMEDIUM":                        "123",
	"ENOMEM":                           "12",
	"ENOMSG":                           "42",
	"ENONET":                           "64",
	"ENOPKG":                           "65",
	"ENOPROTOOPT":                      "92",
	"ENOSPC":                           "28",
	"ENOSR":                            "63",
	"ENOSTR":                           "60",
	"ENOSYS":                           "38",
	"ENOTBLK":                          "15",
	"ENOTCONN":                         "107",
	"ENOTDIR":                          "20",
	"ENOTEMPTY":                        "39",
	"ENOTNAM":                          "118",
	"ENOTRECOVERABLE":                  "131",
	"ENOTSOCK":                         "88",
	"ENOTSUP":                          "95",
	"ENOTTY":                           "25",
	"ENOTUNIQ":                         "76",
	"ENXIO":                            "6",
	"EOPNOTSUPP":                       "95",
	"EOVERFLOW":                        "75",
	"EOWNERDEAD":                       "130",
	"EPERM":                            "1",
	"EPFNOSUPPORT":                     "96",
	"EPIPE":                            "32",
	"EPROTO":                           "71",
	"EPROTONOSUPPORT":                  "93",
	"EPROTOTYPE":                       "91",
	"ERANGE":                           "34",
	"EREMCHG":                          "78",
	"EREMOTE":                          "66",
	"EREMOTEIO":                        "121",
	"ERESTART":                         "85",
	"ERFKILL":                          "132",
	"EROFS":                            "30",
	"ESHUTDOWN":                        "108",
	"ESOCKTNOSUPPORT":                  "94",
	"ESPIPE":                           "29",
	"ESRCH":                            "3",
	"ESRMNT":                           "69",
	"ESTALE":                           "116",
	"ESTRPIPE":                         "86",
	"ETIME":                            "62",
	"ETIMEDOUT":                        "110",
	"ETOOMANYREFS":                     "109",
	"ETXTBSY":                          "26",
	"EUCLEAN":                          "117",
	"EUNATCH":                          "49",
	"EUSERS":                           "87",
	"EWOULDBLOCK":                      "11",
	"EXDEV":                            "18",
	"EXFULL":                           "54",
	"_ASM_GENERIC_ERRNO_BASE_H":        "0",
	"_ASM_GENERIC_ERRNO_H":             "0",
	"_ATFILE_SOURCE":                   "1",
	"_BITS_ERRNO_H":                    "1",
	"_DEFAULT_SOURCE":                  "1",
	"_ERRNO_H":                         "1",
	"_FEATURES_H":                      "1",
	"_LP64":                            "1",
	"_POSIX_C_SOURCE":                  "200809",
	"_POSIX_SOURCE":                    "1",
	"_STDC_PREDEF_H":                   "1",
	"_SYS_CDEFS_H":                     "1",
	"__ATOMIC_ACQUIRE":                 "2",
	"__ATOMIC_ACQ_REL":                 "4",
	"__ATOMIC_CONSUME":                 "1",
	"__ATOMIC_HLE_ACQUIRE":             "65536",
	"__ATOMIC_HLE_RELEASE":             "131072",
	"__ATOMIC_RELAXED":                 "0",
	"__ATOMIC_RELEASE":                 "3",
	"__ATOMIC_SEQ_CST":                 "5",
	"__BEGIN_DECLS":                    "0",
	"__BIGGEST_ALIGNMENT__":            "16",
	"__BYTE_ORDER__":                   "1234",
	"__CHAR_BIT__":                     "8",
	"__COUNTER__":                      "0",
	"__DBL_DECIMAL_DIG__":              "17",
	"__DBL_DIG__":                      "15",
	"__DBL_HAS_DENORM__":               "1",
	"__DBL_HAS_INFINITY__":             "1",
	"__DBL_HAS_QUIET_NAN__":            "1",
	"__DBL_MANT_DIG__":                 "53",
	"__DBL_MAX_10_EXP__":               "308",
	"__DBL_MAX_EXP__":                  "1024",
	"__DBL_MIN_10_EXP__":               "-307",
	"__DBL_MIN_EXP__":                  "-1021",
	"__DEC128_MANT_DIG__":              "34",
	"__DEC128_MAX_EXP__":               "6145",
	"__DEC128_MIN_EXP__":               "-6142",
	"__DEC32_MANT_DIG__":               "7",
	"__DEC32_MAX_EXP__":                "97",
	"__DEC32_MIN_EXP__":                "-94",
	"__DEC64_MANT_DIG__":               "16",
	"__DEC64_MAX_EXP__":                "385",
	"__DEC64_MIN_EXP__":                "-382",
	"__DECIMAL_BID_FORMAT__":           "1",
	"__DECIMAL_DIG__":                  "21",
	"__DEC_EVAL_METHOD__":              "2",
	"__DI__":                           "0",
	"__ELF__":                          "1",
	"__END_DECLS":                      "0",
	"__FINITE_MATH_ONLY__":             "0",
	"__FLOAT_WORD_ORDER__":             "1234",
	"__FLT128_DECIMAL_DIG__":           "36",
	"__FLT128_DIG__":                   "33",
	"__FLT128_HAS_DENORM__":            "1",
	"__FLT128_HAS_INFINITY__":          "1",
	"__FLT128_HAS_QUIET_NAN__":         "1",
	"__FLT128_MANT_DIG__":              "113",
	"__FLT128_MAX_10_EXP__":            "4932",
	"__FLT128_MAX_EXP__":               "16384",
	"__FLT128_MIN_10_EXP__":            "-4931",
	"__FLT128_MIN_EXP__":               "-16381",
	"__FLT32X_DECIMAL_DIG__":           "17",
	"__FLT32X_DIG__":                   "15",
	"__FLT32X_HAS_DENORM__":            "1",
	"__FLT32X_HAS_INFINITY__":          "1",
	"__FLT32X_HAS_QUIET_NAN__":         "1",
	"__FLT32X_MANT_DIG__":              "53",
	"__FLT32X_MAX_10_EXP__":            "308",
	"__FLT32X_MAX_EXP__":               "1024",
	"__FLT32X_MIN_10_EXP__":            "-307",
	"__FLT32X_MIN_EXP__":               "-1021",
	"__FLT32_DECIMAL_DIG__":            "9",
	"__FLT32_DIG__":                    "6",
	"__FLT32_HAS_DENORM__":             "1",
	"__FLT32_HAS_INFINITY__":           "1",
	"__FLT32_HAS_QUIET_NAN__":          "1",
	"__FLT32_MANT_DIG__":               "24",
	"__FLT32_MAX_10_EXP__":             "38",
	"__FLT32_MAX_EXP__":                "128",
	"__FLT32_MIN_10_EXP__":             "-37",
	"__FLT32_MIN_EXP__":                "-125",
	"__FLT64X_DECIMAL_DIG__":           "21",
	"__FLT64X_DIG__":                   "18",
	"__FLT64X_HAS_DENORM__":            "1",
	"__FLT64X_HAS_INFINITY__":          "1",
	"__FLT64X_HAS_QUIET_NAN__":         "1",
	"__FLT64X_MANT_DIG__":              "64",
	"__FLT64X_MAX_10_EXP__":            "4932",
	"__FLT64X_MAX_EXP__":               "16384",
	"__FLT64X_MIN_10_EXP__":            "-4931",
	"__FLT64X_MIN_EXP__":               "-16381",
	"__FLT64_DECIMAL_DIG__":            "17",
	"__FLT64_DIG__":                    "15",
	"__FLT64_HAS_DENORM__":             "1",
	"__FLT64_HAS_INFINITY__":           "1",
	"__FLT64_HAS_QUIET_NAN__":          "1",
	"__FLT64_MANT_DIG__":               "53",
	"__FLT64_MAX_10_EXP__":             "308",
	"__FLT64_MAX_EXP__":                "1024",
	"__FLT64_MIN_10_EXP__":             "-307",
	"__FLT64_MIN_EXP__":                "-1021",
	"__FLT_DECIMAL_DIG__":              "9",
	"__FLT_DIG__":                      "6",
	"__FLT_EVAL_METHOD_TS_18661_3__":   "0",
	"__FLT_EVAL_METHOD__":              "0",
	"__FLT_HAS_DENORM__":               "1",
	"__FLT_HAS_INFINITY__":             "1",
	"__FLT_HAS_QUIET_NAN__":            "1",
	"__FLT_MANT_DIG__":                 "24",
	"__FLT_MAX_10_EXP__":               "38",
	"__FLT_MAX_EXP__":                  "128",
	"__FLT_MIN_10_EXP__":               "-37",
	"__FLT_MIN_EXP__":                  "-125",
	"__FLT_RADIX__":                    "2",
	"__FXSR__":                         "1",
	"__GLIBC_MINOR__":                  "26",
	"__GLIBC_USE_DEPRECATED_GETS":      "0",
	"__GLIBC__":                        "2",
	"__GNU_LIBRARY__":                  "6",
	"__GXX_ABI_VERSION":                "1011",
	"__HAVE_GENERIC_SELECTION":         "1",
	"__HI__":                           "0",
	"__INT16_MAX__":                    "32767",
	"__INT32_MAX__":                    "2147483647",
	"__INT64_MAX__":                    "9223372036854775807",
	"__INT8_MAX__":                     "127",
	"__INTMAX_MAX__":                   "9223372036854775807",
	"__INTMAX_WIDTH__":                 "64",
	"__INTPTR_MAX__":                   "9223372036854775807",
	"__INTPTR_WIDTH__":                 "64",
	"__INT_FAST16_MAX__":               "9223372036854775807",
	"__INT_FAST16_WIDTH__":             "64",
	"__INT_FAST32_MAX__":               "9223372036854775807",
	"__INT_FAST32_WIDTH__":             "64",
	"__INT_FAST64_MAX__":               "9223372036854775807",
	"__INT_FAST64_WIDTH__":             "64",
	"__INT_FAST8_MAX__":                "127",
	"__INT_FAST8_WIDTH__":              "8",
	"__INT_LEAST16_MAX__":              "32767",
	"__INT_LEAST16_WIDTH__":            "16",
	"__INT_LEAST32_MAX__":              "2147483647",
	"__INT_LEAST32_WIDTH__":            "32",
	"__INT_LEAST64_MAX__":              "9223372036854775807",
	"__INT_LEAST64_WIDTH__":            "64",
	"__INT_LEAST8_MAX__":               "127",
	"__INT_LEAST8_WIDTH__":             "8",
	"__INT_MAX__":                      "2147483647",
	"__INT_WIDTH__":                    "32",
	"__KERNEL_STRICT_NAMES":            "0",
	"__LDBL_DECIMAL_DIG__":             "21",
	"__LDBL_DIG__":                     "18",
	"__LDBL_HAS_DENORM__":              "1",
	"__LDBL_HAS_INFINITY__":            "1",
	"__LDBL_HAS_QUIET_NAN__":           "1",
	"__LDBL_MANT_DIG__":                "64",
	"__LDBL_MAX_10_EXP__":              "4932",
	"__LDBL_MAX_EXP__":                 "16384",
	"__LDBL_MIN_10_EXP__":              "-4931",
	"__LDBL_MIN_EXP__":                 "-16381",
	"__LINE__":                         "0",
	"__LONG_LONG_MAX__":                "9223372036854775807",
	"__LONG_LONG_WIDTH__":              "64",
	"__LONG_MAX__":                     "9223372036854775807",
	"__LONG_WIDTH__":                   "64",
	"__LP64__":                         "1",
	"__MMX__":                          "1",
	"__NO_INLINE__":                    "1",
	"__ORDER_BIG_ENDIAN__":             "4321",
	"__ORDER_LITTLE_ENDIAN__":          "1234",
	"__ORDER_PDP_ENDIAN__":             "3412",
	"__PRAGMA_REDEFINE_EXTNAME":        "1",
	"__PTRDIFF_MAX__":                  "9223372036854775807",
	"__PTRDIFF_WIDTH__":                "64",
	"__QI__":                           "0",
	"__REGISTER_PREFIX__":              "0",
	"__SCHAR_MAX__":                    "127",
	"__SCHAR_WIDTH__":                  "8",
	"__SEG_FS":                         "1",
	"__SEG_GS":                         "1",
	"__SHRT_MAX__":                     "32767",
	"__SHRT_WIDTH__":                   "16",
	"__SIG_ATOMIC_MAX__":               "2147483647",
	"__SIG_ATOMIC_MIN__":               "-2147483648",
	"__SIG_ATOMIC_WIDTH__":             "32",
	"__SIZEOF_DOUBLE__":                "8",
	"__SIZEOF_FLOAT128__":              "16",
	"__SIZEOF_FLOAT80__":               "16",
	"__SIZEOF_FLOAT__":                 "4",
	"__SIZEOF_INT128__":                "16",
	"__SIZEOF_INT__":                   "4",
	"__SIZEOF_LONG_DOUBLE__":           "16",
	"__SIZEOF_LONG_LONG__":             "8",
	"__SIZEOF_LONG__":                  "8",
	"__SIZEOF_POINTER__":               "8",
	"__SIZEOF_PTRDIFF_T__":             "8",
	"__SIZEOF_SHORT__":                 "2",
	"__SIZEOF_SIZE_T__":                "8",
	"__SIZEOF_WCHAR_T__":               "4",
	"__SIZEOF_WINT_T__":                "4",
	"__SIZE_MAX__":                     "18446744073709551615u",
	"__SIZE_WIDTH__":                   "64",
	"__SI__":                           "0",
	"__SSE2_MATH__":                    "1",
	"__SSE2__":                         "1",
	"__SSE_MATH__":                     "1",
	"__SSE__":                          "1",
	"__STDC_HOSTED__":                  "1",
	"__STDC_IEC_559_COMPLEX__":         "1",
	"__STDC_IEC_559__":                 "1",
	"__STDC_ISO_10646__":               "201706",
	"__STDC_NO_THREADS__":              "1",
	"__STDC_UTF_16__":                  "1",
	"__STDC_UTF_32__":                  "1",
	"__STDC_VERSION__":                 "201112",
	"__STDC__":                         "1",
	"__SYSCALL_WORDSIZE":               "64",
	"__THROW":                          "0",
	"__THROWNL":                        "0",
	"__UINT16_MAX__":                   "65535",
	"__UINT32_MAX__":                   "4294967295u",
	"__UINT64_MAX__":                   "18446744073709551615u",
	"__UINT8_MAX__":                    "255",
	"__UINTMAX_MAX__":                  "18446744073709551615u",
	"__UINTPTR_MAX__":                  "18446744073709551615u",
	"__UINT_FAST16_MAX__":              "18446744073709551615u",
	"__UINT_FAST32_MAX__":              "18446744073709551615u",
	"__UINT_FAST64_MAX__":              "18446744073709551615u",
	"__UINT_FAST8_MAX__":               "255",
	"__UINT_LEAST16_MAX__":             "65535",
	"__UINT_LEAST32_MAX__":             "4294967295u",
	"__UINT_LEAST64_MAX__":             "18446744073709551615u",
	"__UINT_LEAST8_MAX__":              "255",
	"__USER_LABEL_PREFIX__":            "0",
	"__USE_ATFILE":                     "1",
	"__USE_FORTIFY_LEVEL":              "0",
	"__USE_ISOC11":                     "1",
	"__USE_ISOC95":                     "1",
	"__USE_ISOC99":                     "1",
	"__USE_MISC":                       "1",
	"__USE_POSIX":                      "1",
	"__USE_POSIX199309":                "1",
	"__USE_POSIX199506":                "1",
	"__USE_POSIX2":                     "1",
	"__USE_POSIX_IMPLICITLY":           "1",
	"__USE_XOPEN2K":                    "1",
	"__USE_XOPEN2K8":                   "1",
	"__WCHAR_MAX__":                    "2147483647",
	"__WCHAR_MIN__":                    "-2147483648",
	"__WCHAR_WIDTH__":                  "32",
	"__WINT_MAX__":                     "4294967295u",
	"__WINT_MIN__":                     "0u",
	"__WINT_WIDTH__":                   "32",
	"__WORDSIZE":                       "64",
	"__WORDSIZE_TIME64_COMPAT32":       "1",
	"__always_inline":                  "0",
	"__amd64":                          "1",
	"__amd64__":                        "1",
	"__attribute_artificial__":         "0",
	"__attribute_const__":              "0",
	"__attribute_deprecated__":         "0",
	"__attribute_malloc__":             "0",
	"__attribute_noinline__":           "0",
	"__attribute_pure__":               "0",
	"__attribute_used__":               "0",
	"__attribute_warn_unused_result__": "0",
	"__code_model_small__":             "1",
	"__extension__":                    "0",
	"__glibc_c99_flexarr_available":    "1",
	"__inline":                         "0",
	"__k8":                             "1",
	"__k8__":                           "1",
	"__linux":                          "1",
	"__linux__":                        "1",
	"__restrict":                       "0",
	"__stub___compat_bdflush":          "0",
	"__stub_chflags":                   "0",
	"__stub_fattach":                   "0",
	"__stub_fchflags":                  "0",
	"__stub_fdetach":                   "0",
	"__stub_getmsg":                    "0",
	"__stub_gtty":                      "0",
	"__stub_lchmod":                    "0",
	"__stub_putmsg":                    "0",
	"__stub_revoke":                    "0",
	"__stub_setlogin":                  "0",
	"__stub_sigreturn":                 "0",
	"__stub_sstk":                      "0",
	"__stub_stty":                      "0",
	"__unix":                           "1",
	"__unix__":                         "1",
	"__word__":                         "0",
	"__wur":                            "0",
	"__x86_64":                         "1",
	"__x86_64__":                       "1",
	"linux":                            "1",
	"unix":                             "1",
}

var serrno__ [1]byte
