// Code generated by 'ccgo /tmp/go-generate-587637772/x.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-pkgname pwd -o libc/pwd/pwd_linux_amd64.go', DO NOT EDIT.

package pwd

import (
	"math"
	"reflect"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ unsafe.Pointer

const (
	NSS_BUFLEN_PASSWD     = 1024
	X_ATFILE_SOURCE       = 1
	X_BITS_TYPESIZES_H    = 1
	X_BITS_TYPES_H        = 1
	X_BSD_SIZE_T_         = 0
	X_BSD_SIZE_T_DEFINED_ = 0
	X_DEFAULT_SOURCE      = 1
	X_FEATURES_H          = 1
	X_GCC_SIZE_T          = 0
	X_LP64                = 1
	X_POSIX_C_SOURCE      = 200809
	X_POSIX_SOURCE        = 1
	X_PWD_H               = 1
	X_SIZET_              = 0
	X_SIZE_T              = 0
	X_SIZE_T_             = 0
	X_SIZE_T_DECLARED     = 0
	X_SIZE_T_DEFINED      = 0
	X_SIZE_T_DEFINED_     = 0
	X_STDC_PREDEF_H       = 1
	X_SYS_CDEFS_H         = 1
	X_SYS_SIZE_T_H        = 0
	X_T_SIZE              = 0
	X_T_SIZE_             = 0
	Linux                 = 1
	Unix                  = 1
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

// Wide character type.
//   Locale-writers should change this as necessary to
//   be big enough to hold unique values not between 0 and 127,
//   and not (wchar_t) -1, for each defined multibyte character.

// Define this type if we are doing the whole job,
//   or if we want this type in particular.

//  In 4.3bsd-net2, leave these undefined to indicate that size_t, etc.
//    are already defined.
//  BSD/OS 3.1 and FreeBSD [23].x require the MACHINE_ANSI_H check here.
//  NetBSD 5 requires the I386_ANSI_H and X86_64_ANSI_H checks here.

// A null pointer constant.

// The Single Unix specification says that some more types are
//   available here.
type Gid_t = uint32 /* pwd.h:38:17 */

type Uid_t = uint32 /* pwd.h:43:17 */

// A record in the user database.
type Passwd = struct {
	Fpw_name   uintptr
	Fpw_passwd uintptr
	Fpw_uid    uint32
	Fpw_gid    uint32
	Fpw_gecos  uintptr
	Fpw_dir    uintptr
	Fpw_shell  uintptr
}

var _ int8 /* x.c:2:13: */
